# Generated by Django 4.2.16 on 2024-11-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=17)),
                ('dir_mac', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'estaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'mediciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametrosMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_ide', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_max', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'parametros_medicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReglasMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reglas_medicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('tipo_medicion', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'tipos_medicion',
                'managed': False,
            },
        ),
    ]
