# Generated by Django 4.2.16 on 2024-10-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje_1', models.FloatField()),
                ('voltaje_2', models.FloatField()),
                ('voltaje_3', models.FloatField()),
                ('voltaje_4', models.FloatField()),
                ('voltaje_5', models.FloatField()),
                ('intensidad_1', models.FloatField()),
                ('intensidad_2', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.estacion')),
            ],
        ),
    ]
