# Generated by Django 4.2.16 on 2024-10-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_estacion_nombre_alter_estacion_ubicacion_and_more'),
    ]

    operations = [
    ]
