# Generated by Django 4.2.16 on 2024-10-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_estacion_table_alter_medicion_table'),
    ]

    operations = [
    ]
