# Generated by Django 4.2.16 on 2024-11-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_estacion_table_alter_medicion_table'),
    ]

    operations = [
    ]
