# Generated by Django 4.2.16 on 2024-11-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje1', models.FloatField()),
                ('voltaje2', models.FloatField()),
                ('voltaje3', models.FloatField()),
                ('voltaje4', models.FloatField()),
                ('voltaje5', models.FloatField()),
                ('intensidad1', models.FloatField()),
                ('intensidad2', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
